# Generated by Django 5.1.1 on 2024-09-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
