# Generated by Django 5.1.1 on 2024-09-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evento_usuario', to='agenda.usuario'),
        ),
    ]
