# Generated by Django 5.1.1 on 2024-09-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_categoria_remove_evento_users_alter_evento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
