# Generated by Django 5.1.1 on 2024-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_evento_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
