# Generated by Django 5.1.1 on 2024-09-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_evento_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
