# Generated by Django 5.1.1 on 2024-10-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_bookinstance_id_bookinstance_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isnb',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sumary',
            new_name='summary',
        ),
    ]
